### PR TITLE
FIX: Property normal on MeshVertex is readonly and can not be set

### LINKED ISSUE #1: Script doesn't work with most recent blender version
I am using Blender Version 3.5.1 and the script complained about the property normals on MeshVertex being readonly.

### PR DESCRIPTION
**Pull request by fel-str**
Fixes #1 
Normals on MeshVertex should not be manually modified as by https://projects.blender.org/blender/blender/issues/97018. The script still works anyways.

### CODE REVIEW

**Comment by Puxtril** [comment]
Simply removing the feature isn't a good fix to this problem, is there an alternative to set Normal data?

**Comment by fel-str** [comment]
The default normals for the Mesh are derived from the mesh data itself anyways as I understand it.
Is it possible that the input for normals never changed anything anyways then?
Depending on the implementation of the application you are debugging, you could still just apply an extracted normal map.

I am by no means an expert at this though so correct me if I am wrong.

**Comment by Puxtril** [comment]
If you have normal data, it's always better to apply that. Blender will automatically generate normals but they won't be identical to the source. I actually don't know if normal maps completely replace or modify the mesh's normals. But yes, I do agree most people will end up applying a normal map. 

Regardless, I would rather investigate replacement functionality before completely removing it.

**Comment by TheBigBobo** [comment]
csv import error
[tdac.csv](https://github.com/Puxtril/CSV-Import/files/14157242/tdac.csv)
Not sure if this is the same problem. I'm trying to extract some geometry from DCS to make a controller. I've tried using the normals listed in the CSV and using the position columns instead as you did in the youtube video. Neither work. The CSV doesn't have colour data, I'm not sure if that's a problem.

**Comment by Puxtril** [comment]
Sorry about the _really_ long response time on this. I looked into this and couldn't find a way to integrate normal importing into this script. In any case, I realized the auto-cleanup checkbox (which is checked by default) is overriding normals anyway, so I figure normals are not too important for the average user.

The reason I'm closing this issue is because removing normals is more than just the code in this pull request. There is a bunch of other code that needed tweaking for this to be properly removed. But in any case, I appreciate you creating this.

**Pull request closed without merging**
